[tool.black]
target-version = ["py311",]
force-exclude = '''
(
  config\.py
  | alembic\.ini
  | \.git
  | \.venv
  | build
  | dist
  | venv
  | alembic
  | \.gitignore
  | \.flake8
)
'''

[tool.pylint]
ignore = ['config.py', 'alembic', 'venv']
disable = ["C", "R", "W"]

[tool.flake8]
extend-ignore = "E501"
exclude = ".git,__pycache__,config.py,old,build,dist,alembic,venv,alembic.ini,.gitignore,requirements.txt"
max-complexity = 10
max-line-length = 120