name: Main

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Linter Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autoflake
        run: |
          autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive .

      - name: Run isort
        run: |
          isort .

      - name: Run black
        run: |
          black .

      - name: Run flake8
        run: flake8 .

      - name: Run pylint
        run: pylint ../crypto-listener-bot